[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.branch-deploy]
    command = "mv robots-disallow.txt robots.txt"


[context.production]
    command = "mv robots-production.txt robots.txt"
